.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_800A2EF0, 0x10

glabel func_800A2EF0
    /* 069170 800A2EF0 46006124 */  cvt.w.s    $ft0, $fa0
    /* 069174 800A2EF4 44022000 */  mfc1       $v0, $ft0
    /* 069178 800A2EF8 03E00008 */  jr         $ra
    /* 06917C 800A2EFC 00000000 */   nop
endlabel func_800A2EF0

/* Handwritten function */
nonmatching func_800A2F00, 0x2C

glabel func_800A2F00
    /* 069180 800A2F00 10C00007 */  beqz       $a2, .L800A2F20
    /* 069184 800A2F04 00C44020 */   add       $t0, $a2, $a0 /* handwritten instruction */
  .L800A2F08:
    /* 069188 800A2F08 80890000 */  lb         $t1, 0x0($a0)
    /* 06918C 800A2F0C 24840001 */  addiu      $a0, $a0, 0x1
    /* 069190 800A2F10 00094A00 */  sll        $t1, $t1, 8
    /* 069194 800A2F14 A4A90000 */  sh         $t1, 0x0($a1)
    /* 069198 800A2F18 1488FFFB */  bne        $a0, $t0, .L800A2F08
    /* 06919C 800A2F1C 24A50002 */   addiu     $a1, $a1, 0x2
  .L800A2F20:
    /* 0691A0 800A2F20 00051020 */  add        $v0, $zero, $a1 /* handwritten instruction */
    /* 0691A4 800A2F24 03E00008 */  jr         $ra
    /* 0691A8 800A2F28 00000000 */   nop
endlabel func_800A2F00
    /* 0691AC 800A2F2C 00000000 */  nop
