.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_800A2F30, 0x20

glabel func_800A2F30
    /* 0691B0 800A2F30 24A80080 */  addiu      $t0, $a1, 0x80
  .L800A2F34:
    /* 0691B4 800A2F34 84A90000 */  lh         $t1, 0x0($a1)
    /* 0691B8 800A2F38 24A50002 */  addiu      $a1, $a1, 0x2
    /* 0691BC 800A2F3C 24840002 */  addiu      $a0, $a0, 0x2
    /* 0691C0 800A2F40 14A8FFFC */  bne        $a1, $t0, .L800A2F34
    /* 0691C4 800A2F44 A489FFFE */   sh        $t1, -0x2($a0)
    /* 0691C8 800A2F48 03E00008 */  jr         $ra
    /* 0691CC 800A2F4C 00000000 */   nop
endlabel func_800A2F30

/* Handwritten function */
nonmatching func_800A2F50, 0x60

glabel func_800A2F50
    /* 0691D0 800A2F50 00001025 */  or         $v0, $zero, $zero
    /* 0691D4 800A2F54 24A80080 */  addiu      $t0, $a1, 0x80
  .L800A2F58:
    /* 0691D8 800A2F58 808A0000 */  lb         $t2, 0x0($a0)
  .L800A2F5C:
    /* 0691DC 800A2F5C 80A90000 */  lb         $t1, 0x0($a1)
    /* 0691E0 800A2F60 20A50001 */  addi       $a1, $a1, 0x1 /* handwritten instruction */
    /* 0691E4 800A2F64 112A000E */  beq        $t1, $t2, .L800A2FA0
    /* 0691E8 800A2F68 20840001 */   addi      $a0, $a0, 0x1 /* handwritten instruction */
    /* 0691EC 800A2F6C 012A582A */  slt        $t3, $t1, $t2
    /* 0691F0 800A2F70 15600006 */  bnez       $t3, .L800A2F8C
    /* 0691F4 800A2F74 24020001 */   addiu     $v0, $zero, 0x1
    /* 0691F8 800A2F78 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 0691FC 800A2F7C 54A8FFF6 */  bnel       $a1, $t0, .L800A2F58
    /* 069200 800A2F80 A0A9FFFF */   sb        $t1, -0x1($a1)
    /* 069204 800A2F84 03E00008 */  jr         $ra
    /* 069208 800A2F88 A0A9FFFF */   sb        $t1, -0x1($a1)
  .L800A2F8C:
    /* 06920C 800A2F8C 21290001 */  addi       $t1, $t1, 0x1 /* handwritten instruction */
    /* 069210 800A2F90 54A8FFF1 */  bnel       $a1, $t0, .L800A2F58
    /* 069214 800A2F94 A0A9FFFF */   sb        $t1, -0x1($a1)
    /* 069218 800A2F98 03E00008 */  jr         $ra
    /* 06921C 800A2F9C A0A9FFFF */   sb        $t1, -0x1($a1)
  .L800A2FA0:
    /* 069220 800A2FA0 54A8FFEE */  bnel       $a1, $t0, .L800A2F5C
    /* 069224 800A2FA4 808A0000 */   lb        $t2, 0x0($a0)
    /* 069228 800A2FA8 03E00008 */  jr         $ra
    /* 06922C 800A2FAC 00000000 */   nop
endlabel func_800A2F50

/* Handwritten function */
nonmatching func_800A2FB0, 0x140

glabel func_800A2FB0
    /* 069230 800A2FB0 23BDFFE0 */  addi       $sp, $sp, -0x20 /* handwritten instruction */
    /* 069234 800A2FB4 AFB00000 */  sw         $s0, 0x0($sp)
    /* 069238 800A2FB8 AFB10004 */  sw         $s1, 0x4($sp)
    /* 06923C 800A2FBC AFB20008 */  sw         $s2, 0x8($sp)
    /* 069240 800A2FC0 AFB3000C */  sw         $s3, 0xC($sp)
    /* 069244 800A2FC4 AFB40010 */  sw         $s4, 0x10($sp)
    /* 069248 800A2FC8 AFB50014 */  sw         $s5, 0x14($sp)
    /* 06924C 800A2FCC AFB60018 */  sw         $s6, 0x18($sp)
    /* 069250 800A2FD0 AFB7001C */  sw         $s7, 0x1C($sp)
    /* 069254 800A2FD4 8C900038 */  lw         $s0, 0x38($a0)
    /* 069258 800A2FD8 8C91003C */  lw         $s1, 0x3C($a0)
    /* 06925C 800A2FDC 8C920040 */  lw         $s2, 0x40($a0)
    /* 069260 800A2FE0 8C930044 */  lw         $s3, 0x44($a0)
    /* 069264 800A2FE4 8C940048 */  lw         $s4, 0x48($a0)
    /* 069268 800A2FE8 8C95004C */  lw         $s5, 0x4C($a0)
    /* 06926C 800A2FEC 8C960050 */  lw         $s6, 0x50($a0)
    /* 069270 800A2FF0 8C970054 */  lw         $s7, 0x54($a0)
    /* 069274 800A2FF4 8C870018 */  lw         $a3, 0x18($a0)
    /* 069278 800A2FF8 0290A022 */  sub        $s4, $s4, $s0 /* handwritten instruction */
    /* 06927C 800A2FFC 02B1A822 */  sub        $s5, $s5, $s1 /* handwritten instruction */
    /* 069280 800A3000 02D2B022 */  sub        $s6, $s6, $s2 /* handwritten instruction */
    /* 069284 800A3004 02F3B822 */  sub        $s7, $s7, $s3 /* handwritten instruction */
    /* 069288 800A3008 8C850000 */  lw         $a1, 0x0($a0)
    /* 06928C 800A300C 8C860014 */  lw         $a2, 0x14($a0)
    /* 069290 800A3010 0014A0C3 */  sra        $s4, $s4, 3
    /* 069294 800A3014 0015A8C3 */  sra        $s5, $s5, 3
    /* 069298 800A3018 0016B0C3 */  sra        $s6, $s6, 3
    /* 06929C 800A301C 0017B8C3 */  sra        $s7, $s7, 3
    /* 0692A0 800A3020 24E80040 */  addiu      $t0, $a3, 0x40
  .L800A3024:
    /* 0692A4 800A3024 02506022 */  sub        $t4, $s2, $s0 /* handwritten instruction */
    /* 0692A8 800A3028 02716822 */  sub        $t5, $s3, $s1 /* handwritten instruction */
    /* 0692AC 800A302C 24E90008 */  addiu      $t1, $a3, 0x8
    /* 0692B0 800A3030 02005025 */  or         $t2, $s0, $zero
    /* 0692B4 800A3034 02205825 */  or         $t3, $s1, $zero
    /* 0692B8 800A3038 000C60C3 */  sra        $t4, $t4, 3
    /* 0692BC 800A303C 000D68C3 */  sra        $t5, $t5, 3
  .L800A3040:
    /* 0692C0 800A3040 80D80001 */  lb         $t8, 0x1($a2)
    /* 0692C4 800A3044 80D90000 */  lb         $t9, 0x0($a2)
    /* 0692C8 800A3048 000A7403 */  sra        $t6, $t2, 16
    /* 0692CC 800A304C 0018C080 */  sll        $t8, $t8, 2
    /* 0692D0 800A3050 01D87020 */  add        $t6, $t6, $t8 /* handwritten instruction */
    /* 0692D4 800A3054 000B7C03 */  sra        $t7, $t3, 16
    /* 0692D8 800A3058 000EC203 */  sra        $t8, $t6, 8
    /* 0692DC 800A305C 0019C880 */  sll        $t9, $t9, 2
    /* 0692E0 800A3060 1700000C */  bnez       $t8, .L800A3094
    /* 0692E4 800A3064 01F97820 */   add       $t7, $t7, $t9 /* handwritten instruction */
    /* 0692E8 800A3068 000FCA03 */  sra        $t9, $t7, 8
    /* 0692EC 800A306C 17200009 */  bnez       $t9, .L800A3094
    /* 0692F0 800A3070 00000000 */   nop
    /* 0692F4 800A3074 000E7043 */  sra        $t6, $t6, 1
    /* 0692F8 800A3078 000F7843 */  sra        $t7, $t7, 1
    /* 0692FC 800A307C 000E71C0 */  sll        $t6, $t6, 7
    /* 069300 800A3080 01CF7025 */  or         $t6, $t6, $t7
    /* 069304 800A3084 01C57020 */  add        $t6, $t6, $a1 /* handwritten instruction */
    /* 069308 800A3088 81D90000 */  lb         $t9, 0x0($t6)
    /* 06930C 800A308C 10000002 */  b          .L800A3098
    /* 069310 800A3090 A0F90000 */   sb        $t9, 0x0($a3)
  .L800A3094:
    /* 069314 800A3094 A0E00000 */  sb         $zero, 0x0($a3)
  .L800A3098:
    /* 069318 800A3098 014C5020 */  add        $t2, $t2, $t4 /* handwritten instruction */
    /* 06931C 800A309C 016D5820 */  add        $t3, $t3, $t5 /* handwritten instruction */
    /* 069320 800A30A0 24E70001 */  addiu      $a3, $a3, 0x1
    /* 069324 800A30A4 24C60002 */  addiu      $a2, $a2, 0x2
    /* 069328 800A30A8 5527FFE5 */  bnel       $t1, $a3, .L800A3040
    /* 06932C 800A30AC 00000000 */   nop
    /* 069330 800A30B0 02148020 */  add        $s0, $s0, $s4 /* handwritten instruction */
    /* 069334 800A30B4 02358820 */  add        $s1, $s1, $s5 /* handwritten instruction */
    /* 069338 800A30B8 02569020 */  add        $s2, $s2, $s6 /* handwritten instruction */
    /* 06933C 800A30BC 02779820 */  add        $s3, $s3, $s7 /* handwritten instruction */
    /* 069340 800A30C0 5507FFD8 */  bnel       $t0, $a3, .L800A3024
    /* 069344 800A30C4 00000000 */   nop
    /* 069348 800A30C8 8FB7001C */  lw         $s7, 0x1C($sp)
    /* 06934C 800A30CC 8FB60018 */  lw         $s6, 0x18($sp)
    /* 069350 800A30D0 8FB50014 */  lw         $s5, 0x14($sp)
    /* 069354 800A30D4 8FB40010 */  lw         $s4, 0x10($sp)
    /* 069358 800A30D8 8FB3000C */  lw         $s3, 0xC($sp)
    /* 06935C 800A30DC 8FB20008 */  lw         $s2, 0x8($sp)
    /* 069360 800A30E0 8FB10004 */  lw         $s1, 0x4($sp)
    /* 069364 800A30E4 8FB00000 */  lw         $s0, 0x0($sp)
    /* 069368 800A30E8 03E00008 */  jr         $ra
    /* 06936C 800A30EC 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_800A2FB0

/* Handwritten function */
nonmatching func_800A30F0, 0x1B4

glabel func_800A30F0
    /* 069370 800A30F0 23BDFFE0 */  addi       $sp, $sp, -0x20 /* handwritten instruction */
    /* 069374 800A30F4 AFB00000 */  sw         $s0, 0x0($sp)
    /* 069378 800A30F8 AFB10004 */  sw         $s1, 0x4($sp)
    /* 06937C 800A30FC AFB20008 */  sw         $s2, 0x8($sp)
    /* 069380 800A3100 AFB3000C */  sw         $s3, 0xC($sp)
    /* 069384 800A3104 AFB40010 */  sw         $s4, 0x10($sp)
    /* 069388 800A3108 AFB50014 */  sw         $s5, 0x14($sp)
    /* 06938C 800A310C AFB60018 */  sw         $s6, 0x18($sp)
    /* 069390 800A3110 AFB7001C */  sw         $s7, 0x1C($sp)
    /* 069394 800A3114 8C900038 */  lw         $s0, 0x38($a0)
    /* 069398 800A3118 8C940048 */  lw         $s4, 0x48($a0)
    /* 06939C 800A311C 8C880034 */  lw         $t0, 0x34($a0)
    /* 0693A0 800A3120 8C91003C */  lw         $s1, 0x3C($a0)
    /* 0693A4 800A3124 0290A022 */  sub        $s4, $s4, $s0 /* handwritten instruction */
    /* 0693A8 800A3128 02880018 */  mult       $s4, $t0
    /* 0693AC 800A312C 8C95004C */  lw         $s5, 0x4C($a0)
    /* 0693B0 800A3130 8C920040 */  lw         $s2, 0x40($a0)
    /* 0693B4 800A3134 8C960050 */  lw         $s6, 0x50($a0)
    /* 0693B8 800A3138 02B1A822 */  sub        $s5, $s5, $s1 /* handwritten instruction */
    /* 0693BC 800A313C 8C930044 */  lw         $s3, 0x44($a0)
    /* 0693C0 800A3140 02D2B022 */  sub        $s6, $s6, $s2 /* handwritten instruction */
    /* 0693C4 800A3144 8C970054 */  lw         $s7, 0x54($a0)
    /* 0693C8 800A3148 8C85001C */  lw         $a1, 0x1C($a0)
    /* 0693CC 800A314C 8C860018 */  lw         $a2, 0x18($a0)
    /* 0693D0 800A3150 0000A010 */  mfhi       $s4
    /* 0693D4 800A3154 02F3B822 */  sub        $s7, $s7, $s3 /* handwritten instruction */
    /* 0693D8 800A3158 8C870014 */  lw         $a3, 0x14($a0)
    /* 0693DC 800A315C 02A80018 */  mult       $s5, $t0
    /* 0693E0 800A3160 0000A810 */  mfhi       $s5
    /* 0693E4 800A3164 00000000 */  nop
    /* 0693E8 800A3168 00000000 */  nop
    /* 0693EC 800A316C 02C80018 */  mult       $s6, $t0
    /* 0693F0 800A3170 0000B010 */  mfhi       $s6
    /* 0693F4 800A3174 00000000 */  nop
    /* 0693F8 800A3178 00000000 */  nop
    /* 0693FC 800A317C 02E80018 */  mult       $s7, $t0
    /* 069400 800A3180 8C88002C */  lw         $t0, 0x2C($a0)
    /* 069404 800A3184 01054020 */  add        $t0, $t0, $a1 /* handwritten instruction */
    /* 069408 800A3188 0000B810 */  mfhi       $s7
    /* 06940C 800A318C 00000000 */  nop
    /* 069410 800A3190 00000000 */  nop
  .L800A3194:
    /* 069414 800A3194 8C820030 */  lw         $v0, 0x30($a0)
    /* 069418 800A3198 02506022 */  sub        $t4, $s2, $s0 /* handwritten instruction */
    /* 06941C 800A319C 02716822 */  sub        $t5, $s3, $s1 /* handwritten instruction */
    /* 069420 800A31A0 01820018 */  mult       $t4, $v0
    /* 069424 800A31A4 8C890020 */  lw         $t1, 0x20($a0)
    /* 069428 800A31A8 02005025 */  or         $t2, $s0, $zero
    /* 06942C 800A31AC 02205825 */  or         $t3, $s1, $zero
    /* 069430 800A31B0 01254820 */  add        $t1, $t1, $a1 /* handwritten instruction */
    /* 069434 800A31B4 00006010 */  mfhi       $t4
    /* 069438 800A31B8 00000000 */  nop
    /* 06943C 800A31BC 00000000 */  nop
    /* 069440 800A31C0 01A20018 */  mult       $t5, $v0
    /* 069444 800A31C4 00006810 */  mfhi       $t5
    /* 069448 800A31C8 00000000 */  nop
    /* 06944C 800A31CC 00000000 */  nop
  .L800A31D0:
    /* 069450 800A31D0 80F80001 */  lb         $t8, 0x1($a3)
    /* 069454 800A31D4 000A7403 */  sra        $t6, $t2, 16
    /* 069458 800A31D8 80F90000 */  lb         $t9, 0x0($a3)
    /* 06945C 800A31DC 01D87020 */  add        $t6, $t6, $t8 /* handwritten instruction */
    /* 069460 800A31E0 000B7C03 */  sra        $t7, $t3, 16
    /* 069464 800A31E4 000E0A03 */  sra        $at, $t6, 8
    /* 069468 800A31E8 1420000C */  bnez       $at, .L800A321C
    /* 06946C 800A31EC 01F97820 */   add       $t7, $t7, $t9 /* handwritten instruction */
    /* 069470 800A31F0 000F0A03 */  sra        $at, $t7, 8
    /* 069474 800A31F4 14200009 */  bnez       $at, .L800A321C
    /* 069478 800A31F8 00000000 */   nop
    /* 06947C 800A31FC 8C810000 */  lw         $at, 0x0($a0)
    /* 069480 800A3200 000E7042 */  srl        $t6, $t6, 1
    /* 069484 800A3204 000F7842 */  srl        $t7, $t7, 1
    /* 069488 800A3208 000E71C0 */  sll        $t6, $t6, 7
    /* 06948C 800A320C 01CF7025 */  or         $t6, $t6, $t7
    /* 069490 800A3210 01C17020 */  add        $t6, $t6, $at /* handwritten instruction */
    /* 069494 800A3214 10000003 */  b          .L800A3224
    /* 069498 800A3218 91D90000 */   lbu       $t9, 0x0($t6)
  .L800A321C:
    /* 06949C 800A321C 8C810000 */  lw         $at, 0x0($a0)
    /* 0694A0 800A3220 90390000 */  lbu        $t9, 0x0($at)
  .L800A3224:
    /* 0694A4 800A3224 90B80000 */  lbu        $t8, 0x0($a1)
    /* 0694A8 800A3228 8C820008 */  lw         $v0, 0x8($a0)
    /* 0694AC 800A322C 0019CA00 */  sll        $t9, $t9, 8
    /* 0694B0 800A3230 0338C825 */  or         $t9, $t9, $t8
    /* 0694B4 800A3234 0019C840 */  sll        $t9, $t9, 1
    /* 0694B8 800A3238 00591020 */  add        $v0, $v0, $t9 /* handwritten instruction */
    /* 0694BC 800A323C 84580000 */  lh         $t8, 0x0($v0)
    /* 0694C0 800A3240 014C5020 */  add        $t2, $t2, $t4 /* handwritten instruction */
    /* 0694C4 800A3244 016D5820 */  add        $t3, $t3, $t5 /* handwritten instruction */
    /* 0694C8 800A3248 24A50001 */  addiu      $a1, $a1, 0x1
    /* 0694CC 800A324C 24C60002 */  addiu      $a2, $a2, 0x2
    /* 0694D0 800A3250 24E70002 */  addiu      $a3, $a3, 0x2
    /* 0694D4 800A3254 A4D8FFFE */  sh         $t8, -0x2($a2)
    /* 0694D8 800A3258 5525FFDD */  bnel       $t1, $a1, .L800A31D0
    /* 0694DC 800A325C 00000000 */   nop
    /* 0694E0 800A3260 02148020 */  add        $s0, $s0, $s4 /* handwritten instruction */
    /* 0694E4 800A3264 02358820 */  add        $s1, $s1, $s5 /* handwritten instruction */
    /* 0694E8 800A3268 02569020 */  add        $s2, $s2, $s6 /* handwritten instruction */
    /* 0694EC 800A326C 02779820 */  add        $s3, $s3, $s7 /* handwritten instruction */
    /* 0694F0 800A3270 5505FFC8 */  bnel       $t0, $a1, .L800A3194
    /* 0694F4 800A3274 00000000 */   nop
    /* 0694F8 800A3278 8FB7001C */  lw         $s7, 0x1C($sp)
    /* 0694FC 800A327C 8FB60018 */  lw         $s6, 0x18($sp)
    /* 069500 800A3280 8FB50014 */  lw         $s5, 0x14($sp)
    /* 069504 800A3284 8FB40010 */  lw         $s4, 0x10($sp)
    /* 069508 800A3288 8FB3000C */  lw         $s3, 0xC($sp)
    /* 06950C 800A328C 8FB20008 */  lw         $s2, 0x8($sp)
    /* 069510 800A3290 8FB10004 */  lw         $s1, 0x4($sp)
    /* 069514 800A3294 8FB00000 */  lw         $s0, 0x0($sp)
    /* 069518 800A3298 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 06951C 800A329C 03E00008 */  jr         $ra
    /* 069520 800A32A0 24020000 */   addiu     $v0, $zero, 0x0
endlabel func_800A30F0
    /* 069524 800A32A4 00000000 */  nop
    /* 069528 800A32A8 00000000 */  nop
    /* 06952C 800A32AC 00000000 */  nop
