.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching func_800A32B0, 0x30

glabel func_800A32B0
    /* 069530 800A32B0 00804825 */  or         $t1, $a0, $zero
    /* 069534 800A32B4 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 069538 800A32B8 01214824 */  and        $t1, $t1, $at
    /* 06953C 800A32BC 01254825 */  or         $t1, $t1, $a1
    /* 069540 800A32C0 2401FFFB */  addiu      $at, $zero, -0x5
    /* 069544 800A32C4 01214824 */  and        $t1, $t1, $at
    /* 069548 800A32C8 40899000 */  mtc0       $t1, $18 /* handwritten instruction */
    /* 06954C 800A32CC 24090000 */  addiu      $t1, $zero, 0x0
    /* 069550 800A32D0 01294825 */  or         $t1, $t1, $t1
    /* 069554 800A32D4 40899800 */  mtc0       $t1, $19 /* handwritten instruction */
    /* 069558 800A32D8 03E00008 */  jr         $ra
    /* 06955C 800A32DC 24080000 */   addiu     $t0, $zero, 0x0
endlabel func_800A32B0

/* Handwritten function */
nonmatching func_800A32E0, 0x1C

glabel func_800A32E0
    /* 069560 800A32E0 01084025 */  or         $t0, $t0, $t0
    /* 069564 800A32E4 40889000 */  mtc0       $t0, $18 /* handwritten instruction */
    /* 069568 800A32E8 24090000 */  addiu      $t1, $zero, 0x0
    /* 06956C 800A32EC 01294825 */  or         $t1, $t1, $t1
    /* 069570 800A32F0 40899800 */  mtc0       $t1, $19 /* handwritten instruction */
    /* 069574 800A32F4 03E00008 */  jr         $ra
    /* 069578 800A32F8 00000000 */   nop
endlabel func_800A32E0
    /* 06957C 800A32FC 00000000 */  nop
