.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching func_800A8FA0, 0x28

glabel func_800A8FA0
    /* 06F220 800A8FA0 10C00006 */  beqz       $a2, .L800A8FBC
    /* 06F224 800A8FA4 00C54020 */   add       $t0, $a2, $a1 /* handwritten instruction */
  .L800A8FA8:
    /* 06F228 800A8FA8 8CA90000 */  lw         $t1, 0x0($a1)
    /* 06F22C 800A8FAC 24A50004 */  addiu      $a1, $a1, 0x4
    /* 06F230 800A8FB0 AC890000 */  sw         $t1, 0x0($a0)
    /* 06F234 800A8FB4 14A8FFFC */  bne        $a1, $t0, .L800A8FA8
    /* 06F238 800A8FB8 24840004 */   addiu     $a0, $a0, 0x4
  .L800A8FBC:
    /* 06F23C 800A8FBC 00041020 */  add        $v0, $zero, $a0 /* handwritten instruction */
    /* 06F240 800A8FC0 03E00008 */  jr         $ra
    /* 06F244 800A8FC4 00000000 */   nop
endlabel func_800A8FA0

/* Handwritten function */
nonmatching func_800A8FC8, 0x20

glabel func_800A8FC8
    /* 06F248 800A8FC8 10A00004 */  beqz       $a1, .L800A8FDC
  .L800A8FCC:
    /* 06F24C 800A8FCC A4860000 */   sh        $a2, 0x0($a0)
    /* 06F250 800A8FD0 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 06F254 800A8FD4 14A0FFFD */  bnez       $a1, .L800A8FCC
    /* 06F258 800A8FD8 24840002 */   addiu     $a0, $a0, 0x2
  .L800A8FDC:
    /* 06F25C 800A8FDC 00041020 */  add        $v0, $zero, $a0 /* handwritten instruction */
    /* 06F260 800A8FE0 03E00008 */  jr         $ra
    /* 06F264 800A8FE4 00000000 */   nop
endlabel func_800A8FC8

/* Handwritten function */
nonmatching func_800A8FE8, 0x20

glabel func_800A8FE8
    /* 06F268 800A8FE8 10C00004 */  beqz       $a2, .L800A8FFC
    /* 06F26C 800A8FEC 00C44020 */   add       $t0, $a2, $a0 /* handwritten instruction */
  .L800A8FF0:
    /* 06F270 800A8FF0 A0850000 */  sb         $a1, 0x0($a0)
    /* 06F274 800A8FF4 1488FFFE */  bne        $a0, $t0, .L800A8FF0
    /* 06F278 800A8FF8 24840001 */   addiu     $a0, $a0, 0x1
  .L800A8FFC:
    /* 06F27C 800A8FFC 00041020 */  add        $v0, $zero, $a0 /* handwritten instruction */
    /* 06F280 800A9000 03E00008 */  jr         $ra
    /* 06F284 800A9004 00000000 */   nop
endlabel func_800A8FE8
    /* 06F288 800A9008 00000000 */  nop
    /* 06F28C 800A900C 00000000 */  nop
