.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

/* Handwritten function */
glabel func_8003AD80
/* 001000 8003AD80 3C08800E */  lui        $t0, %hi(main_BSS_START)
/* 001004 8003AD84 3C090004 */  lui        $t1, (0x4D8C0 >> 16)
/* 001008 8003AD88 25081F10 */  addiu      $t0, $t0, %lo(main_BSS_START)
/* 00100C 8003AD8C 3529D8C0 */  ori        $t1, $t1, (0x4D8C0 & 0xFFFF)
.L8003AD90:
/* 001010 8003AD90 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
/* 001014 8003AD94 AD000000 */  sw         $zero, 0x0($t0)
/* 001018 8003AD98 AD000004 */  sw         $zero, 0x4($t0)
/* 00101C 8003AD9C 1520FFFC */  bnez       $t1, .L8003AD90
/* 001020 8003ADA0 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
/* 001024 8003ADA4 3C0A8005 */  lui        $t2, %hi(boot)
/* 001028 8003ADA8 3C1D8010 */  lui        $sp, %hi(bootStack + 0x2000)
/* 00102C 8003ADAC 254A9CE0 */  addiu      $t2, $t2, %lo(boot)
/* 001030 8003ADB0 01400008 */  jr         $t2
/* 001034 8003ADB4 27BD56D0 */   addiu     $sp, $sp, %lo(bootStack + 0x2000)
/* 001038 8003ADB8 00000000 */  nop
/* 00103C 8003ADBC 00000000 */  nop
/* 001040 8003ADC0 00000000 */  nop
/* 001044 8003ADC4 00000000 */  nop
/* 001048 8003ADC8 00000000 */  nop
/* 00104C 8003ADCC 00000000 */  nop
